name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # runs when the main branch is changed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # this is for our deploy steps

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.7.0'

      - name: Build Projects
        run: |
          # build the first tensorflow project
          cd projects/learning-tensorflowjs/first-proj/first-tensorflow-proj/
          npm install
          npm run build
          cd ../../../..

          # second tensorflow project
          cd projects/learning-tensorflowjs/second-proj-image-recognition/image-recognition-tensorflowjs/
          npm install
          npm run build
          cd ../../../..

          # threeJS project
          cd projects/threeJS-practice/puzzler/
          npm install
          npm run build
          cd ../../..

      - name: Prepare Deployment Dir
        run: |
          # make temp dir (we replace the contents of the gh-pages branch with the contents of the dir)
          mkdir gh-pages-temp

          # grab our homepage
          cp index.html gh-pages-temp/

          # grab any of our vite apps
          cp -r projects/learning-tensorflowjs/first-proj/first-tensorflow-proj/dist gh-pages-temp/tf-number-predictor
          cp -r projects/learning-tensorflowjs/second-proj-image-recognition/image-recognition-tensorflowjs/dist gh-pages-temp/tf-image-recognition
          cp -r projects/threeJS-practice/puzzler/dist gh-pages-temp/threeJS-practice

      - name: Deploy temp dir to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages-temp
          destination_dir: ''
          cname: ''
